name: Run Selenium Script Daily

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:
jobs:
  selenium-job:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{secrets.EMAIL}}
      PASSWORD: ${{secrets.PASSWORD}}
      URL: ${{secrets.URL}}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium Script
        run: python checker.py
